In [6]:
import numpy as np
x=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
print(x[0,0:2])

[0 1]


In [8]:
print(x[0,1:])

[1 2 3]


In [9]:
print(x[1:2,0:1])

[[4]]


In [10]:
print(x[1:3,1:4])

[[ 5  6  7]
 [ 9 10 11]]


In [11]:
print(x[1:,0:1])

[[4]
 [8]]


In [12]:
print(x[1:2,:1])

[[4]]


In [13]:
print(x[1:,1:])

[[ 5  6  7]
 [ 9 10 11]]


In [14]:
a=np.array([[8,20,24,25],[30,35,36,40],[42,43,47,50],[49,51,52,52]])
print(a)

[[ 8 20 24 25]
 [30 35 36 40]
 [42 43 47 50]
 [49 51 52 52]]


In [15]:
print(a[1:3,1:3])

[[35 36]
 [43 47]]


In [16]:
print(a[2: ,1:])

[[43 47 50]
 [51 52 52]]


In [17]:
print(a[0:2,2:])

[[24 25]
 [36 40]]


In [18]:
import pandas as pd
x=pd.DataFrame({'rollno':[101,102,103],'name':['atharv','raj','om']},index=[0,1,2],columns=("rollno","name"))
print(x)

   rollno    name
0     101  atharv
1     102     raj
2     103      om


In [19]:
x.describe()

rollno
count     3.0
mean    102.0
std       1.0
min     101.0
25%     101.5
50%     102.0
75%     102.5
max     103.0

In [20]:
x.head(2)

rollno    name
0     101  atharv
1     102     raj

In [21]:
x.tail(2)

rollno name
1     102  raj
2     103   om

In [25]:
x={'rollno':[101,102,103],'name':['atharv','raj','om']}